dist: xenial # ubuntu 16.04 LTS, EOL April 2021
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "10"
  - "8"
  - "6"
  - "4"
cache:
  directories:
    - node_modules
    - $HOME/.gradle
    - .gradle
script:
  - npm test
jobs:
  include:
    - stage: npm release
      node_js: "8" # This *has* to be the "build leader"
      script: skip
      after_success:
        - npm run semantic-release
branches:
  only:
    - master
