os:
  - linux
sudo: false
notifications:
  email: false
language: node_js
jdk:
  - openjdk8
node_js:
  - "10"
  - "8"
  - "6"
env:
  - GRADLE_VERSION=3.5.1 JAVA_VERSION=openjdk8

  - GRADLE_VERSION=4.10.3 JAVA_VERSION=openjdk8

  - GRADLE_VERSION=5.3.1 JAVA_VERSION=openjdk8

cache:
  directories:
    - node_modules
    - $HOME/.gradle
    - .gradle
before_install:
  # sdkman helps to install different gradle versions
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
after_success:
  - travis_terminate 0 # try to make Windows quit
script:
  - export GRADLE_OPTS=-Dorg.gradle.daemon=false
  - sdk install gradle $GRADLE_VERSION
  - jdk_switcher use $JAVA_VERSION
  - npm test
jobs:
  include:
    - stage: npm release
      node_js: "8" # This *has* to be the "build leader"
      script: skip
      after_success:
        - npx semantic-release
branches:
  only:
    - master
