# https://www.appveyor.com/docs/appveyor-yml

os: Visual Studio 2015
platform:
  - x64
# to disable automatic builds
build: off
branches:
  only:
    - master

init:
  - git config --global core.autocrlf true

shallow_clone: true
clone_depth: 1

cache:
  - node_modules -> package.json

environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - npm install
  - choco install gradle
  # During the first run, Gradle prints "Welcome to Gradle!" banner, even with -q
  # so, run it once to ensure stdout won't be polluted anymore
  - gradle -v

test_script:
  - npm run test
